apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infra/infra.namespace.yml
  - tekton/tekton.namespace.yml
  - tekton/work.namespace.yml
bases:
  - infra
  - tekton
