apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton
resources:
  - tekton-storage.yml
  - tekton-dashboard.yml
  - tekton.ingress.yml
patchesStrategicMerge:
  - config-artifact-bucket.yml
helmCharts:
  - name: tekton-pipeline
    releaseName: tekton-pipeline
    repo: https://cdfoundation.github.io/tekton-helm-chart/
    valuesInline:
