apiVersion: v1
kind: Secret
metadata:
  name: tekton-storage
type: kubernetes.io/opaque
stringData:
  boto-config: |
    [Credentials]
    aws_access_key_id = 
    aws_secret_access_key = 
    [s3]
    host = 
    [Boto]
    https_validate_certificates = True
