apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  dev.cyphers.service: cert-manager
helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    releaseName: cert-manager
    valuesInline:
      installCRDs: true
      prometheus: # Setup prometheus eventually
        enabled: false
      global:
        leaderElection:
          namespace: "infra"
