apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: digitalocean-issuer
spec:
  acme:
    email: devyncyphers@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: digitalocean-issuer
    solvers:
      - selector: {}
        dns01:
          digitalocean:
            tokenSecretRef:
              name: do-access-token
              key: access-token
