apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: do-access-token
    envs:
      - do.env
resources:
  - ./digitalocean.issuer.yml
generatorOptions:
  disableNameSuffixHash: true
