apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  dev.cyphers.service: traefik
configMapGenerator:
  - name: traefik-config
    files:
      - ./traefik.yml
resources:
  - "./charts/traefik/crds/ingressroute.yaml"
  - "./charts/traefik/crds/ingressroutetcp.yaml"
  - "./charts/traefik/crds/ingressrouteudp.yaml"
  - "./charts/traefik/crds/middlewares.yaml"
  - "./charts/traefik/crds/middlewarestcp.yaml"
  - "./charts/traefik/crds/serverstransports.yaml"
  - "./charts/traefik/crds/tlsoptions.yaml"
  - "./charts/traefik/crds/tlsstores.yaml"
  - "./charts/traefik/crds/traefikservices.yaml"
helmCharts:
  - name: traefik
    repo: https://helm.traefik.io/traefik
    releaseName: traefik
    valuesInline:
      logs:
        general:
          level: DEBUG
      ingressClass:
        enabled: true
        isDefaultClass: true
        fallbackApiVersion: v1beta1
      ingressRoute:
        dashboard:
          enabled: false
      volumes:
        - name: traefik-config
          mountPath: "/config"
          type: configMap
      persistence:
        enabled: false
      securityContext:
        capabilities:
          drop: [ALL]
          add: [NET_BIND_SERVICE]
        readOnlyRootFilesystem: false
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
      ports:
        traefik:
          healthchecksPort: 8000
        web:
          redirectTo: websecure
      additionalArguments:
        - "--configFile=/config/traefik.yml"
