api:
  debug: false
  dashboard: false
global:
  sendAnonymousUsage: false
providers:
  kubernetesCRD:
    namespaces: []
ping:
  entryPoint: web
entryPoints:
  web:
    address: :8000
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :8443
